# Generated by Django 2.2.1 on 2019-05-29 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentChoiceDateAndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.CharField(default='All', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentChoiceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(default='All', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body_promotion', models.TextField(default='body_promotion', max_length=25)),
                ('full_promotion', models.TextField(default='full_promotion', max_length=250)),
                ('image_promotion', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_client', models.CharField(default='name', max_length=25, null=True)),
                ('second_name_of_client', models.CharField(default='None', max_length=30, null=True)),
                ('phone_number_of_client', models.CharField(max_length=10, null=True)),
                ('date_appointment_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('chooise_appointment_service', models.ManyToManyField(related_name='choice_service', to='Chernysheva_nail.AppointmentChoiceService')),
                ('date_and_time_appointment', models.ManyToManyField(related_name='choice_date', to='Chernysheva_nail.AppointmentChoiceDateAndTime')),
            ],
        ),
    ]
